### ISSUE TITLE
Update SY projects to newer version

### ISSUE THREAD

**Issue by apodhrad** [windup/soa-migration#12]
Current version is 0.8.1.Final which is old and it causes that the first lab cannot be deployed into new SOA 6 (currently ER6) due to changes as follows:
- jca:resourceAdapter doesn't contain attribute type
- jca:activationSpec doesn't contain attribute type

**Comment by poojamalini** [comment]
Hello, 
I face an issue when running the windup 2.1.0 with the SOA5 rule that was provided. 
How did you run it successfully?
Attaching the error:
[bin]$ windup-migrate-app --input C:\online_Dispatcher --output C:\results
Overwrite all contents of "C:\results" (anything already in the directory will b
e deleted)? [y/N]  y
Properties: {index.search.directory=C:\results\graph\graphsearch, cache.db-cache
-time=0, cache.db-cache=true, index.search.backend=lucene, cache.db-cache-size=0
.05, cache.db-cache-clean-wait=0, storage.backend=berkeleyje, storage.directory=
C:\results\graph\titangraph, storage.berkeleydb.cache-percentage=1}
Using user rules dir: C:\Users\pooja.malini\.windup\rules
Using user rules dir: C:\windup-distribution-2.1.0.A-offline\windup-distribution
-2.1.0.A\rules
***ERROR*** Error while executing 'Windup Migrate App'
org.jboss.windup.util.exception.WindupException: Failed to parse XML configurati
on at: file:/C:/windup-distribution-2.1.0.A-offline/windup-distribution-2.1.0.A/
rules/extensions/soa5.windup.xml due to: No Handler registered for element named
 [beans] in namespace: [http://www.springframework.org/schema/beans]
        at org.jboss.windup.config.parser.XMLRuleProviderLoader.getProviders(XML
RuleProviderLoader.java:123)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoad
erInterceptor.java:87)
        at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java
:42)
        at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoad
erInterceptor.java:103)
        at org.jboss.windup.config.parser.XMLRuleProviderLoader_$$_javassist_4fb
9151f-1835-4f4a-9dcc-559864769c04.getProviders(XMLRuleProviderLoader_$$_javassis
t_4fb9151f-1835-4f4a-9dcc-559864769c04.java)
        at org.jboss.windup.config.loader.WindupRuleLoaderImpl.getProviders(Wind
upRuleLoaderImpl.java:115)
        at org.jboss.windup.config.loader.WindupRuleLoaderImpl.build(WindupRuleL
oaderImpl.java:133)
        at org.jboss.windup.config.loader.WindupRuleLoaderImpl.loadConfiguration
(WindupRuleLoaderImpl.java:58)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoad
erInterceptor.java:87)
        at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java
:42)
        at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoad
erInterceptor.java:103)
        at org.jboss.windup.config.loader.WindupRuleLoaderImpl_$$_javassist_5103
c6e2-93eb-433c-b954-5ea133bae674.loadConfiguration(WindupRuleLoaderImpl_$$_javas
sist_5103c6e2-93eb-433c-b954-5ea133bae674.java)
        at org.jboss.windup.exec.WindupProcessorImpl.execute(WindupProcessorImpl
.java:88)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoad
erInterceptor.java:87)
        at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java
:42)
        at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoad
erInterceptor.java:103)
        at org.jboss.windup.exec.WindupProcessorImpl_$$_javassist_272ff08a-1592-
44d3-999d-61480d269532.execute(WindupProcessorImpl_$$_javassist_272ff08a-1592-44
d3-999d-61480d269532.java)
        at org.jboss.windup.ui.WindupCommand.execute(WindupCommand.java:243)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoad
erInterceptor.java:87)
        at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java
:42)
        at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoad
erInterceptor.java:103)
        at org.jboss.windup.ui.WindupCommand_$$_javassist_db95da1c-fbd6-4bc8-9ed
e-f168f82e8c21.execute(WindupCommand_$$_javassist_db95da1c-fbd6-4bc8-9ede-f168f8
2e8c21.java)
        at org.jboss.forge.addon.ui.impl.controller.SingleCommandControllerImpl.
execute(SingleCommandControllerImpl.java:90)
        at org.jboss.forge.addon.shell.aesh.CommandAdapter.execute(CommandAdapte
r.java:74)
        at org.jboss.aesh.console.AeshConsoleImpl$AeshConsoleCallbackImpl.execut
e(AeshConsoleImpl.java:325)
        at org.jboss.aesh.console.AeshProcess.run(AeshProcess.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.jboss.windup.config.exception.ConfigurationException: No Handler
registered for element named [beans] in namespace: [http://www.springframework.o
rg/schema/beans]
        at org.jboss.windup.config.parser.ParserContext.processElement(ParserCon
text.java:88)
        at org.jboss.windup.config.parser.XMLRuleProviderLoader.getProviders(XML
RuleProviderLoader.java:118)
        ... 44 more
***ERROR*** Failed to parse XML configuration at: file:/C:/windup-distribution-2
.1.0.A-offline/windup-distribution-2.1.0.A/rules/extensions/soa5.windup.xml due
to: No Handler registered for element named [beans] in namespace: [http://www.sp
ringframework.org/schema/beans]
